#!/usr/bin/env bash
# install-systemd-units.sh — drop service + timer into systemd and
# enable. Generates a drop-in for the running user + source paths.
#
# Idempotent. Re-run after adding sources to update ReadWritePaths.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

if [[ $EUID -ne 0 ]]; then
  die "needs root — re-run via 'sudo install-systemd-units.sh'"
fi

# We need to know which non-root user owns ~/.config/restic-backup,
# because that's where the env files live. SUDO_USER is the canonical
# answer when invoked via sudo.
TARGET_USER="${SUDO_USER:-root}"
TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
[[ -n "$TARGET_HOME" ]] || die "could not resolve home for user ${TARGET_USER}"

CFG="${TARGET_HOME}/.config/restic-backup"
SOURCES="${CFG}/sources.list"
[[ -r "$SOURCES" ]] || die "no sources list at ${SOURCES} — run init-repos.sh + add-source.sh first"

# Install the runner script into a stable path so the unit's
# ExecStart points somewhere that doesn't depend on the user's clone.
RUNNER_DIR="/usr/local/lib/restic-backup"
mkdir -p "$RUNNER_DIR"
install -m 0755 "${SKILL_DIR}/scripts/run-backup.sh" "${RUNNER_DIR}/run-backup.sh"
install -m 0755 "${SKILL_DIR}/scripts/lib.sh"        "${RUNNER_DIR}/lib.sh"
ok "installed runner at ${RUNNER_DIR}/"

# Drop service + timer.
install -m 0644 "${SKILL_DIR}/systemd/restic-backup.service" /etc/systemd/system/restic-backup.service
install -m 0644 "${SKILL_DIR}/systemd/restic-backup.timer"   /etc/systemd/system/restic-backup.timer

# Generate a drop-in for User= and ReadWritePaths.
DROP_IN_DIR="/etc/systemd/system/restic-backup.service.d"
mkdir -p "$DROP_IN_DIR"

# Build ReadWritePaths from sources.list. We need /var/log + the
# user's config dir + every backed-up source.
RW_PATHS="/var/log ${CFG}"
while IFS=$'\t ' read -r SRC _; do
  case "$SRC" in
    ""|\#*) continue ;;
  esac
  RW_PATHS="${RW_PATHS} ${SRC}"
done < "$SOURCES"

cat > "${DROP_IN_DIR}/override.conf" <<EOF
# Auto-generated by install-systemd-units.sh — re-run after adding sources.
[Service]
User=${TARGET_USER}
EnvironmentFile=-${CFG}/nas.env
EnvironmentFile=-${CFG}/r2.env
EnvironmentFile=-${CFG}/healthcheck.env
ReadOnlyPaths=
ReadWritePaths=${RW_PATHS}
ExecStart=
ExecStart=${RUNNER_DIR}/run-backup.sh
EOF

systemctl daemon-reload
systemctl enable restic-backup.timer
systemctl start  restic-backup.timer

ok "service + timer installed and enabled"
log "next scheduled run:"
systemctl list-timers restic-backup.timer --no-pager | sed 's/^/    /'
log "trigger an immediate run with: sudo systemctl start restic-backup.service"
log "tail logs with: journalctl -fu restic-backup.service"
